# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_mentalhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('client_id', models.CharField(default=None, max_length=10, null=True, blank=True)),
                ('depression', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('hyperactivity', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('bedWetting', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('bipolar', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('suicideAttempt', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('physicalAbuse', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('law', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('LD', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('tic', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('thyroid', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('heart', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('overweight', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('mood', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('alcohol', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('drugs', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('schizo', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('seizures', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('completedSuicide', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('sexAbuse', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('panic', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('anxiety', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('OCD', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('diabetes', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('cancer', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('highBloodPressure', models.CharField(default=None, max_length=35, null=True, blank=True)),
                ('anger', models.CharField(default=None, max_length=35, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UseTable',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('client_id', models.CharField(default=None, max_length=10, null=True, blank=True)),
                ('howMuch1', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften1', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong1', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld1', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime1', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch2', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften2', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong2', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld2', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime2', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch3', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften3', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong3', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld3', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime3', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch4', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften4', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong4', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld4', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime4', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch5', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften5', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong5', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld5', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime5', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch6', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften6', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong6', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld6', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime6', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch7', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften7', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong7', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld7', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime7', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch8', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften8', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong8', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld8', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime8', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch9', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften9', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong9', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld9', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime9', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch10', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften10', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong10', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld10', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime10', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch11', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften11', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong11', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld11', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime11', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch12', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften12', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong12', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld12', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime12', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch13', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften13', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong13', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld13', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime13', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch14', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften14', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong14', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld14', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime14', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch15', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften15', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong15', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld15', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime15', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch16', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften16', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong16', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld16', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime16', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch17', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften17', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong17', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld17', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime17', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch18', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften18', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong18', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld18', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime18', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch19', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften19', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong19', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld19', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime19', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch20', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften20', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong20', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld20', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime20', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howMuch21', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOften21', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howLong21', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('howOld21', models.CharField(default=None, max_length=15, null=True, blank=True)),
                ('lastTime21', models.CharField(default=None, max_length=15, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='client',
            name='isMale',
            field=models.BooleanField(default=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='birthplace',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='drug_alcohol_use',
            field=models.ForeignKey(default=None, blank=True, to='assessment.UseTable', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='employedMo',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='employedYrs',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='employer',
            field=models.CharField(default=None, max_length=30, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='no_marriages',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='occupation',
            field=models.CharField(default=None, max_length=30, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='pastJobs',
            field=models.CharField(default=None, max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mentalhealth',
            name='raised',
            field=models.CharField(default=None, max_length=20, null=True, blank=True),
            preserve_default=True,
        ),
    ]
