# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0072_am_demographic_wholiveswithclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sap',
            old_name='demoComplet',
            new_name='clinicalComplete',
        ),
        migrations.RenameField(
            model_name='sap',
            old_name='finalComplete',
            new_name='otherComplete',
        ),
        migrations.RenameField(
            model_name='sap',
            old_name='preFinalComplete',
            new_name='psycho2Complete',
        ),
        migrations.RenameField(
            model_name='sap',
            old_name='psychoactive2Complet',
            new_name='psychoComplete',
        ),
        migrations.RenameField(
            model_name='sap',
            old_name='psychoactiveComplet',
            new_name='socialComplete',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age1',
            new_name='alcoholAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug1',
            new_name='alcoholFrequency',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug10',
            new_name='alcoholHow',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug11',
            new_name='alcoholLast',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug12',
            new_name='alcoholQuantity',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age10',
            new_name='amphAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug2',
            new_name='amphFrequency',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug3',
            new_name='amphHow',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug4',
            new_name='amphLast',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug5',
            new_name='amphQuantity',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age11',
            new_name='caffineAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug6',
            new_name='caffineFrequency',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug7',
            new_name='caffineHow',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug8',
            new_name='caffineLast',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='drug9',
            new_name='caffineQuantity',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age12',
            new_name='cokeAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age2',
            new_name='hallAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age3',
            new_name='inhaleAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age4',
            new_name='opAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age5',
            new_name='otherAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age6',
            new_name='pcpAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age7',
            new_name='sedAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age8',
            new_name='smokeAge',
        ),
        migrations.RenameField(
            model_name='sappsychoactive',
            old_name='age9',
            new_name='weedAge',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency1',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency10',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency11',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency12',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency2',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency3',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency4',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency5',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency6',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency7',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency8',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='frequency9',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how1',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how10',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how11',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how12',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how2',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how3',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how4',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how5',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how6',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how7',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how8',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='how9',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last1',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last10',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last11',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last12',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last2',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last3',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last4',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last5',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last6',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last7',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last8',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='last9',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity1',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity10',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity11',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity12',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity2',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity3',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity4',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity5',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity6',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity7',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity8',
        ),
        migrations.RemoveField(
            model_name='sappsychoactive',
            name='quantity9',
        ),
        migrations.AddField(
            model_name='sap',
            name='sourcesComplete',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sapdemographics',
            name='isChild',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sapdemographics',
            name='isDual',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sapdemographics',
            name='isNone',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sapdemographics',
            name='isOther',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sapdemographics',
            name='isSenior',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='cokeFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='cokeHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='cokeLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='cokeQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='hallFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='hallHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='hallLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='hallQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='inhaleFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='inhaleHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='inhaleLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='inhaleQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='opFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='opHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='opLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='opQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='otherFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='otherHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='otherLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='otherQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='pcpFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='pcpHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='pcpLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='pcpQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='sedFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='sedHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='sedLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='sedQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='smokeFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='smokeHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='smokeLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='smokeQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='weedFrequency',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='weedHow',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='weedLast',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sappsychoactive',
            name='weedQuantity',
            field=models.CharField(default=None, max_length=25, null=True, blank=True),
            preserve_default=True,
        ),
    ]
