# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0110_auto_20160712_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ais_social1',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f18dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f18yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f19dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f19yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f20dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f20yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f21dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f21yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f22dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f22yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f23dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f23yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f24dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f24yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f25dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f25yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f26dayBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='f26yearBad',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa18',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa19',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa20',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa21',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa22',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa23',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa24',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa25',
        ),
        migrations.RemoveField(
            model_name='ais_social2',
            name='fa26',
        ),
        migrations.AddField(
            model_name='ais_social2',
            name='d27d',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ais_social2',
            name='d27y',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ais_social2',
            name='d28d',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ais_social2',
            name='d28y',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ais_social2',
            name='d29d',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ais_social2',
            name='d29y',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ais_social1',
            name='f37',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ais_social1',
            name='f38',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ais_social1',
            name='f7',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ais_social1',
            name='f8',
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
    ]
